version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    env_file:
        - .env
    volumes:
      - .:/workspaces:cached
    ports:
      - 8080:8080
    depends_on:
      - db
    platform: ${PLATFORM}
    command: air -- -buildvcs=false

  db:
    image: groonga/pgroonga:3.0.8-alpine-15-slim
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  
  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: service:app
