// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: recipe.sql

package db

import (
	"context"
)

const createRecipe = `-- name: CreateRecipe :one
SELECT
    id, chef_id, usr_id, name, servings, method, image_url, introduction, link, access_level, created_at, updated_at
FROM
    insert_recipe($1)
`

func (q *Queries) CreateRecipe(ctx context.Context, data []byte) (VRecipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, data)
	var i VRecipe
	err := row.Scan(
		&i.ID,
		&i.ChefID,
		&i.UsrID,
		&i.Name,
		&i.Servings,
		&i.Method,
		&i.ImageUrl,
		&i.Introduction,
		&i.Link,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
