// Package docs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package docs

import (
	"encoding/json"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// CreateChef defines model for CreateChef.
type CreateChef struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`

	// ImageUrl プロフィール画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `json:"link"`

	// Name 登録名
	Name string `json:"name"`

	// NumFollower フォロワー数
	NumFollower int `json:"numFollower"`

	// NumRecipe レシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile シェフ紹介
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// CreateChefRecipe defines model for CreateChefRecipe.
type CreateChefRecipe struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `json:"accessLevel"`

	// ChefId シェフID
	ChefId    openapi_types.UUID `json:"chefId"`
	CreatedAt string             `json:"createdAt"`

	// Id レシピID
	Id openapi_types.UUID `json:"id"`

	// ImageUrl 画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Ingredient 材料
	Ingredient []struct {
		Id openapi_types.UUID `json:"id"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link *[]string `json:"link,omitempty"`

	// Method 作り方
	Method []struct {
		Html       *string                             `json:"html,omitempty"`
		Supplement *CreateChefRecipe_Method_Supplement `json:"supplement,omitempty"`
	} `json:"method"`

	// Name レシピ名
	Name string `json:"name"`

	// NumFav いいね数
	NumFav int `json:"numFav"`

	// Servings ＊人前
	Servings  int    `json:"servings"`
	UpdatedAt string `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId *openapi_types.UUID `json:"usrId,omitempty"`
}

// CreateChefRecipeMethodSupplement0 defines model for .
type CreateChefRecipeMethodSupplement0 = map[string]interface{}

// CreateChefRecipeMethodSupplement1 defines model for .
type CreateChefRecipeMethodSupplement1 = []map[string]interface{}

// CreateChefRecipe_Method_Supplement defines model for CreateChefRecipe.Method.Supplement.
type CreateChefRecipe_Method_Supplement struct {
	union json.RawMessage
}

// CreateShoppingList defines model for CreateShoppingList.
type CreateShoppingList struct {
	CreatedAt string `json:"createdAt"`

	// Description 「*人前」「メモリスト」
	Description *string `json:"description,omitempty"`

	// Id 買い物リストID
	Id openapi_types.UUID `json:"id"`

	// IsFairCopy true：清書、false：下書き
	IsFairCopy bool `json:"isFairCopy"`

	// Item 買い物明細
	Item []struct {
		// Id 買い物明細ID
		Id openapi_types.UUID `json:"id"`

		// IngredientId 材料ID
		IngredientId *openapi_types.UUID `json:"ingredientId,omitempty"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"item"`

	// RIdx リバースインデックス
	RIdx int `json:"rIdx"`

	// RecipeId レシピID
	RecipeId  *openapi_types.UUID `json:"recipeId,omitempty"`
	UpdatedAt string              `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId openapi_types.UUID `json:"usrId"`
}

// CreateUsrRecipe defines model for CreateUsrRecipe.
type CreateUsrRecipe struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `json:"accessLevel"`

	// ChefId シェフID
	ChefId    *openapi_types.UUID `json:"chefId,omitempty"`
	CreatedAt string              `json:"createdAt"`

	// Id レシピID
	Id openapi_types.UUID `json:"id"`

	// ImageUrl 画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Ingredient 材料
	Ingredient []struct {
		Id openapi_types.UUID `json:"id"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link *[]string `json:"link,omitempty"`

	// Method 作り方
	Method []struct {
		Html       *string                            `json:"html,omitempty"`
		Supplement *CreateUsrRecipe_Method_Supplement `json:"supplement,omitempty"`
	} `json:"method"`

	// Name レシピ名
	Name string `json:"name"`

	// NumFav いいね数
	NumFav int `json:"numFav"`

	// Servings ＊人前
	Servings  int    `json:"servings"`
	UpdatedAt string `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId openapi_types.UUID `json:"usrId"`
}

// CreateUsrRecipeMethodSupplement0 defines model for .
type CreateUsrRecipeMethodSupplement0 = map[string]interface{}

// CreateUsrRecipeMethodSupplement1 defines model for .
type CreateUsrRecipeMethodSupplement1 = []map[string]interface{}

// CreateUsrRecipe_Method_Supplement defines model for CreateUsrRecipe.Method.Supplement.
type CreateUsrRecipe_Method_Supplement struct {
	union json.RawMessage
}

// DeletedChef defines model for DeletedChef.
type DeletedChef struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`

	// ImageUrl プロフィール画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name 登録名
	Name string `json:"name"`

	// NumFollower フォロワー数
	NumFollower int `json:"numFollower"`

	// NumRecipe レシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile シェフ紹介
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// DeletedRecipe defines model for DeletedRecipe.
type DeletedRecipe struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `json:"accessLevel"`

	// ChefId シェフID
	ChefId    *openapi_types.UUID `json:"chefId,omitempty"`
	CreatedAt string              `json:"createdAt"`

	// Id レシピID
	Id openapi_types.UUID `json:"id"`

	// ImageUrl 画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link *[]string `json:"link,omitempty"`

	// Name レシピ名
	Name string `json:"name"`

	// NumFav いいね数
	NumFav int `json:"numFav"`

	// Servings ＊人前
	Servings  int    `json:"servings"`
	UpdatedAt string `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId *openapi_types.UUID `json:"usrId,omitempty"`
}

// DeletedShoppingList defines model for DeletedShoppingList.
type DeletedShoppingList struct {
	CreatedAt string `json:"createdAt"`

	// Description 「*人前」「メモリスト」
	Description *string `json:"description,omitempty"`

	// Id 買い物リストID
	Id openapi_types.UUID `json:"id"`

	// IsFairCopy true：清書、false：下書き
	IsFairCopy bool `json:"isFairCopy"`

	// RIdx リバースインデックス
	RIdx int `json:"rIdx"`

	// RecipeId レシピID
	RecipeId  *openapi_types.UUID `json:"recipeId,omitempty"`
	UpdatedAt string              `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId openapi_types.UUID `json:"usrId"`
}

// DeletedUsr defines model for DeletedUsr.
type DeletedUsr struct {
	CreatedAt string `json:"createdAt"`

	// Email ログインemail
	Email string `json:"email"`
	Id    string `json:"id"`

	// ImageUrl プロフィール画像（任意）
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name ニックネーム
	Name string `json:"name"`

	// NumRecipe マイレシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile 自己紹介（任意）
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// FeaturedChef defines model for FeaturedChef.
type FeaturedChef struct {
	Data []struct {
		// ChefId シェフID
		ChefId openapi_types.UUID `json:"chefId"`

		// ImageUrl プロフィール画像
		ImageUrl *string `json:"imageUrl,omitempty"`

		// Name シェフ登録名
		Name string `json:"name"`

		// NumFollower フォロワー数
		NumFollower int `json:"numFollower"`

		// Score 注目度→実際のデータはscoreの降順でソートされる
		Score int `json:"score"`
	} `json:"data"`
}

// GetChef defines model for GetChef.
type GetChef struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`

	// ImageUrl プロフィール画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `json:"link"`

	// Name 登録名
	Name string `json:"name"`

	// NumFollower フォロワー数
	NumFollower int `json:"numFollower"`

	// NumRecipe レシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile シェフ紹介
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// GetRecipe defines model for GetRecipe.
type GetRecipe struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `json:"accessLevel"`

	// ChefId シェフID
	ChefId    *openapi_types.UUID `json:"chefId,omitempty"`
	CreatedAt string              `json:"createdAt"`

	// Id レシピID
	Id openapi_types.UUID `json:"id"`

	// ImageUrl 画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Ingredient 材料
	Ingredient []struct {
		Id openapi_types.UUID `json:"id"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link *[]string `json:"link,omitempty"`

	// Method 作り方
	Method []struct {
		Html       *string                      `json:"html,omitempty"`
		Supplement *GetRecipe_Method_Supplement `json:"supplement,omitempty"`
	} `json:"method"`

	// Name レシピ名
	Name string `json:"name"`

	// NumFav いいね数
	NumFav int `json:"numFav"`

	// Servings ＊人前
	Servings  int    `json:"servings"`
	UpdatedAt string `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId *openapi_types.UUID `json:"usrId,omitempty"`
}

// GetRecipeMethodSupplement0 defines model for .
type GetRecipeMethodSupplement0 = map[string]interface{}

// GetRecipeMethodSupplement1 defines model for .
type GetRecipeMethodSupplement1 = []map[string]interface{}

// GetRecipe_Method_Supplement defines model for GetRecipe.Method.Supplement.
type GetRecipe_Method_Supplement struct {
	union json.RawMessage
}

// GetShoppingList defines model for GetShoppingList.
type GetShoppingList struct {
	// ChefName 有名シェフ名
	ChefName  *string `json:"chefName,omitempty"`
	CreatedAt string  `json:"createdAt"`

	// Description 「*人前」「メモリスト」
	Description *string `json:"description,omitempty"`

	// GeneralChefName 一般シェフ名
	GeneralChefName *string `json:"generalChefName,omitempty"`

	// Id 買い物リストID
	Id openapi_types.UUID `json:"id"`

	// IsFairCopy true：清書、false：下書き
	IsFairCopy bool `json:"isFairCopy"`

	// Item 買い物明細
	Item []struct {
		// Id 買い物明細ID
		Id openapi_types.UUID `json:"id"`

		// IngredientId 材料ID
		IngredientId *openapi_types.UUID `json:"ingredientId,omitempty"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"item"`

	// RIdx リバースインデックス
	RIdx     int                 `json:"rIdx"`
	RecipeId *openapi_types.UUID `json:"recipeId,omitempty"`

	// RecipeName レシピ名
	RecipeName string `json:"recipeName"`
	UpdatedAt  string `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId openapi_types.UUID `json:"usrId"`
}

// GetShoppingLists defines model for GetShoppingLists.
type GetShoppingLists struct {
	Data []struct {
		// ChefName 有名シェフ名
		ChefName  *string `json:"chefName,omitempty"`
		CreatedAt string  `json:"createdAt"`

		// Description 「*人前」「メモリスト」
		Description *string `json:"description,omitempty"`

		// GeneralChefName 一般シェフ名
		GeneralChefName *string `json:"generalChefName,omitempty"`

		// Id 買い物リストID
		Id openapi_types.UUID `json:"id"`

		// IsFairCopy true：清書、false：下書き
		IsFairCopy bool `json:"isFairCopy"`

		// Item 買い物明細
		Item []struct {
			// Id 買い物明細ID
			Id openapi_types.UUID `json:"id"`

			// IngredientId 材料ID
			IngredientId *openapi_types.UUID `json:"ingredientId,omitempty"`

			// Name 材料名
			Name string `json:"name"`

			// Supplement 補足
			Supplement *string `json:"supplement,omitempty"`
		} `json:"item"`

		// RIdx リバースインデックス
		RIdx int `json:"rIdx"`

		// RecipeId レシピID
		RecipeId *openapi_types.UUID `json:"recipeId,omitempty"`

		// RecipeName レシピ名
		RecipeName string `json:"recipeName"`
		UpdatedAt  string `json:"updatedAt"`

		// UsrId ユーザーID
		UsrId openapi_types.UUID `json:"usrId"`
	} `json:"data"`
}

// GetUsr defines model for GetUsr.
type GetUsr struct {
	CreatedAt string `json:"createdAt"`

	// Email ログインemail
	Email string `json:"email"`
	Id    string `json:"id"`

	// ImageUrl プロフィール画像（任意）
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク（任意）
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `json:"link"`

	// Name ニックネーム
	Name string `json:"name"`

	// NumRecipe マイレシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile 自己紹介（任意）
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// SearchChef defines model for SearchChef.
type SearchChef struct {
	Data *[]struct {
		CreatedAt string `json:"createdAt"`
		Id        string `json:"id"`

		// ImageUrl プロフィール画像
		ImageUrl *string `json:"imageUrl,omitempty"`

		// Name 登録名
		Name string `json:"name"`

		// NumFollower フォロワー数
		NumFollower int `json:"numFollower"`

		// NumRecipe レシピ数
		NumRecipe int `json:"numRecipe"`

		// Profile シェフ紹介
		Profile   *string `json:"profile,omitempty"`
		UpdatedAt string  `json:"updatedAt"`
	} `json:"data,omitempty"`
}

// SearchChefRecipe defines model for SearchChefRecipe.
type SearchChefRecipe struct {
	Data *[]struct {
		// AccessLevel 公開、限定公開、非公開、下書き
		AccessLevel int    `json:"accessLevel"`
		ChefId      string `json:"chefId"`
		CreatedAt   string `json:"createdAt"`
		Id          string `json:"id"`

		// ImageUrl 画像
		ImageUrl *string `json:"imageUrl,omitempty"`

		// Introduction レシピの紹介文
		Introduction *string `json:"introduction,omitempty"`

		// Name レシピ名
		Name string `json:"name"`

		// NumFav いいね数
		NumFav int `json:"numFav"`

		// Servings ＊人前
		Servings  int    `json:"servings"`
		UpdatedAt string `json:"updatedAt"`
	} `json:"data,omitempty"`
}

// TrendRecipe defines model for TrendRecipe.
type TrendRecipe struct {
	Data []struct {
		// ImageUrl レシピ画像
		ImageUrl *string `json:"imageUrl,omitempty"`

		// Introduction レシピの紹介文
		Introduction *string `json:"introduction,omitempty"`

		// Name レシピ名
		Name string `json:"name"`

		// NumFav ファボられ数
		NumFav int `json:"numFav"`

		// RecipeId レシピID
		RecipeId openapi_types.UUID `json:"recipeId"`

		// Score 話題度→実際のデータはscoreの降順でソートされる
		Score int `json:"score"`
	} `json:"data"`
}

// UpdateChef defines model for UpdateChef.
type UpdateChef struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`

	// ImageUrl プロフィール画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `json:"link"`

	// Name 登録名
	Name string `json:"name"`

	// NumFollower フォロワー数
	NumFollower int `json:"numFollower"`

	// NumRecipe レシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile シェフ紹介
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// UpdateRecipe defines model for UpdateRecipe.
type UpdateRecipe struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `json:"accessLevel"`

	// ChefId シェフID
	ChefId    *openapi_types.UUID `json:"chefId,omitempty"`
	CreatedAt string              `json:"createdAt"`

	// Id レシピID
	Id openapi_types.UUID `json:"id"`

	// ImageUrl 画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Ingredient 材料
	Ingredient []struct {
		Id openapi_types.UUID `json:"id"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link *[]string `json:"link,omitempty"`

	// Method 作り方
	Method []struct {
		Html       *string                         `json:"html,omitempty"`
		Supplement *UpdateRecipe_Method_Supplement `json:"supplement,omitempty"`
	} `json:"method"`

	// Name レシピ名
	Name string `json:"name"`

	// NumFav いいね数
	NumFav int `json:"numFav"`

	// Servings ＊人前
	Servings  int    `json:"servings"`
	UpdatedAt string `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId *openapi_types.UUID `json:"usrId,omitempty"`
}

// UpdateRecipeMethodSupplement0 defines model for .
type UpdateRecipeMethodSupplement0 = map[string]interface{}

// UpdateRecipeMethodSupplement1 defines model for .
type UpdateRecipeMethodSupplement1 = []map[string]interface{}

// UpdateRecipe_Method_Supplement defines model for UpdateRecipe.Method.Supplement.
type UpdateRecipe_Method_Supplement struct {
	union json.RawMessage
}

// UpdateShoppingList defines model for UpdateShoppingList.
type UpdateShoppingList struct {
	CreatedAt string `json:"createdAt"`

	// Description 「*人前」「メモリスト」
	Description *string `json:"description,omitempty"`

	// Id 買い物リストID
	Id openapi_types.UUID `json:"id"`

	// IsFairCopy true：清書、false：下書き
	IsFairCopy bool `json:"isFairCopy"`

	// Item 買い物明細
	Item []struct {
		// Id 買い物明細ID
		Id openapi_types.UUID `json:"id"`

		// IngredientId 材料ID
		IngredientId *openapi_types.UUID `json:"ingredientId,omitempty"`

		// Name 材料名
		Name string `json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `json:"item"`

	// RIdx リバースインデックス
	RIdx int `json:"rIdx"`

	// RecipeId レシピID
	RecipeId  *openapi_types.UUID `json:"recipeId,omitempty"`
	UpdatedAt string              `json:"updatedAt"`

	// UsrId ユーザーID
	UsrId openapi_types.UUID `json:"usrId"`
}

// UpdateUsr defines model for UpdateUsr.
type UpdateUsr struct {
	CreatedAt string `json:"createdAt"`

	// Email ログインemail
	Email string `json:"email"`
	Id    string `json:"id"`

	// ImageUrl プロフィール画像（任意）
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク（任意）
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `json:"link"`

	// Name ニックネーム
	Name string `json:"name"`

	// NumRecipe マイレシピ数
	NumRecipe int `json:"numRecipe"`

	// Profile 自己紹介（任意）
	Profile   *string `json:"profile,omitempty"`
	UpdatedAt string  `json:"updatedAt"`
}

// PostApiChefsJSONBody defines parameters for PostApiChefs.
type PostApiChefsJSONBody struct {
	// ImageUrl プロフィール画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `binding:"required" json:"link"`

	// Name 登録名
	Name string `binding:"required" json:"name"`

	// Profile シェフ紹介
	Profile *string `json:"profile,omitempty"`
}

// GetApiChefsRecipeSearchParams defines parameters for GetApiChefsRecipeSearch.
type GetApiChefsRecipeSearchParams struct {
	// Q 全文検索テキスト
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PutApiChefsRecipeRecipeIdJSONBody defines parameters for PutApiChefsRecipeRecipeId.
type PutApiChefsRecipeRecipeIdJSONBody struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `binding:"required" json:"accessLevel"`

	// ImageUrl 画像
	ImageUrl   *string `json:"imageUrl,omitempty"`
	Ingredient []struct {
		// Id 材料ID
		Id *openapi_types.UUID `json:"id,omitempty"`

		// Name 材料名
		Name string `binding:"required" json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `binding:"required" json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link []string `binding:"required" json:"link"`

	// Method 作り方
	Method []struct {
		Html *string `json:"html,omitempty"`

		// Supplement 補足
		Supplement *any `json:"supplement,omitempty"`
	} `binding:"required" json:"method"`

	// Name レシピ名
	Name string `binding:"required" json:"name"`

	// Servings ＊人前
	Servings int `binding:"required" json:"servings"`
}

// GetApiChefsSearchParams defines parameters for GetApiChefsSearch.
type GetApiChefsSearchParams struct {
	// Q 全文検索テキスト
	Q string `form:"q" json:"q"`
}

// PostApiChefsChefIdRecipeJSONBody defines parameters for PostApiChefsChefIdRecipe.
type PostApiChefsChefIdRecipeJSONBody struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `binding:"required" json:"accessLevel"`

	// ImageUrl 画像
	ImageUrl   *string `json:"imageUrl,omitempty"`
	Ingredient []struct {
		// Name 材料名
		Name string `binding:"required" json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `binding:"required" json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link []string `binding:"required" json:"link"`

	// Method 作り方
	Method []struct {
		Html *string `json:"html,omitempty"`

		// Supplement 補足
		Supplement *any `json:"supplement,omitempty"`
	} `binding:"required" json:"method"`

	// Name レシピ名
	Name string `binding:"required" json:"name"`

	// Servings ＊人前
	Servings int `binding:"required" json:"servings"`
}

// PutApiChefsIdJSONBody defines parameters for PutApiChefsId.
type PutApiChefsIdJSONBody struct {
	// ImageUrl プロフィール画像
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `binding:"required" json:"link"`

	// Name 登録名
	Name string `binding:"required" json:"name"`

	// Profile シェフ紹介
	Profile *string `json:"profile,omitempty"`
}

// PostApiUserListsJSONBody defines parameters for PostApiUserLists.
type PostApiUserListsJSONBody struct {
	// Description 「*人前」「メモリスト」
	Description *string `json:"description,omitempty"`

	// IsFairCopy true：清書、false：下書き
	IsFairCopy bool `binding:"required" json:"isFairCopy"`

	// Item 買い物明細
	Item []struct {
		// IngredientId 材料ID（メモリストのときはnull）
		IngredientId *string `json:"ingredientId,omitempty"`

		// Name 材料名
		Name string `binding:"required" json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `binding:"required" json:"item"`

	// RecipeId レシピID（メモリストのときはnull）
	RecipeId *string `json:"recipeId,omitempty"`
}

// PutApiUserListsIdJSONBody defines parameters for PutApiUserListsId.
type PutApiUserListsIdJSONBody struct {
	// Description 「*人前」「メモリスト」
	Description *string `json:"description,omitempty"`

	// IsFairCopy true：清書、false：下書き
	IsFairCopy bool `binding:"required" json:"isFairCopy"`

	// Item 買い物明細
	Item []struct {
		// Id 買い物明細ID（新規登録のときはnull）
		Id *string `json:"id,omitempty"`

		// IngredientId 材料ID（メモリストのときはnull）
		IngredientId *string `json:"ingredientId,omitempty"`

		// Name 材料名
		Name string `binding:"required" json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `binding:"required" json:"item"`

	// RIdx リバースインデックス
	RIdx int `binding:"required" json:"rIdx"`

	// RecipeId レシピID（メモリストのときはnull）
	RecipeId *string `json:"recipeId,omitempty"`
}

// PutApiUserUsersJSONBody defines parameters for PutApiUserUsers.
type PutApiUserUsersJSONBody struct {
	// ImageUrl プロフィール画像（任意）
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Link リンク（任意）
	Link []struct {
		Label *string `json:"label,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `binding:"required" json:"link"`

	// Name ニックネーム
	Name string `binding:"required" json:"name"`

	// Profile 自己紹介（任意）
	Profile *string `json:"profile,omitempty"`
}

// PostApiUserUsersRecipeJSONBody defines parameters for PostApiUserUsersRecipe.
type PostApiUserUsersRecipeJSONBody struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `binding:"required" json:"accessLevel"`

	// ImageUrl 画像
	ImageUrl   *string `json:"imageUrl,omitempty"`
	Ingredient []struct {
		// Name 材料名
		Name string `binding:"required" json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `binding:"required" json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link []string `binding:"required" json:"link"`

	// Method 作り方
	Method []struct {
		Html *string `json:"html,omitempty"`

		// Supplement 補足
		Supplement *any `json:"supplement,omitempty"`
	} `binding:"required" json:"method"`

	// Name レシピ名
	Name string `binding:"required" json:"name"`

	// Servings ＊人前
	Servings int `binding:"required" json:"servings"`
}

// PutApiUserUsersRecipeRecipeIdJSONBody defines parameters for PutApiUserUsersRecipeRecipeId.
type PutApiUserUsersRecipeRecipeIdJSONBody struct {
	// AccessLevel 公開、限定公開、非公開、下書き
	AccessLevel int `binding:"required" json:"accessLevel"`

	// ImageUrl 画像
	ImageUrl   *string `json:"imageUrl,omitempty"`
	Ingredient []struct {
		// Id 材料ID
		Id *openapi_types.UUID `json:"id,omitempty"`

		// Name 材料名
		Name string `binding:"required" json:"name"`

		// Supplement 補足
		Supplement *string `json:"supplement,omitempty"`
	} `binding:"required" json:"ingredient"`

	// Introduction レシピの紹介文
	Introduction *string `json:"introduction,omitempty"`

	// Link リンク
	Link []string `binding:"required" json:"link"`

	// Method 作り方
	Method []struct {
		Html *string `json:"html,omitempty"`

		// Supplement 補足
		Supplement *any `json:"supplement,omitempty"`
	} `binding:"required" json:"method"`

	// Name レシピ名
	Name string `binding:"required" json:"name"`

	// Servings ＊人前
	Servings int `binding:"required" json:"servings"`
}

// PostApiChefsJSONRequestBody defines body for PostApiChefs for application/json ContentType.
type PostApiChefsJSONRequestBody PostApiChefsJSONBody

// PutApiChefsRecipeRecipeIdJSONRequestBody defines body for PutApiChefsRecipeRecipeId for application/json ContentType.
type PutApiChefsRecipeRecipeIdJSONRequestBody PutApiChefsRecipeRecipeIdJSONBody

// PostApiChefsChefIdRecipeJSONRequestBody defines body for PostApiChefsChefIdRecipe for application/json ContentType.
type PostApiChefsChefIdRecipeJSONRequestBody PostApiChefsChefIdRecipeJSONBody

// PutApiChefsIdJSONRequestBody defines body for PutApiChefsId for application/json ContentType.
type PutApiChefsIdJSONRequestBody PutApiChefsIdJSONBody

// PostApiUserListsJSONRequestBody defines body for PostApiUserLists for application/json ContentType.
type PostApiUserListsJSONRequestBody PostApiUserListsJSONBody

// PutApiUserListsIdJSONRequestBody defines body for PutApiUserListsId for application/json ContentType.
type PutApiUserListsIdJSONRequestBody PutApiUserListsIdJSONBody

// PutApiUserUsersJSONRequestBody defines body for PutApiUserUsers for application/json ContentType.
type PutApiUserUsersJSONRequestBody PutApiUserUsersJSONBody

// PostApiUserUsersRecipeJSONRequestBody defines body for PostApiUserUsersRecipe for application/json ContentType.
type PostApiUserUsersRecipeJSONRequestBody PostApiUserUsersRecipeJSONBody

// PutApiUserUsersRecipeRecipeIdJSONRequestBody defines body for PutApiUserUsersRecipeRecipeId for application/json ContentType.
type PutApiUserUsersRecipeRecipeIdJSONRequestBody PutApiUserUsersRecipeRecipeIdJSONBody

// AsCreateChefRecipeMethodSupplement0 returns the union data inside the CreateChefRecipe_Method_Supplement as a CreateChefRecipeMethodSupplement0
func (t CreateChefRecipe_Method_Supplement) AsCreateChefRecipeMethodSupplement0() (CreateChefRecipeMethodSupplement0, error) {
	var body CreateChefRecipeMethodSupplement0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChefRecipeMethodSupplement0 overwrites any union data inside the CreateChefRecipe_Method_Supplement as the provided CreateChefRecipeMethodSupplement0
func (t *CreateChefRecipe_Method_Supplement) FromCreateChefRecipeMethodSupplement0(v CreateChefRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChefRecipeMethodSupplement0 performs a merge with any union data inside the CreateChefRecipe_Method_Supplement, using the provided CreateChefRecipeMethodSupplement0
func (t *CreateChefRecipe_Method_Supplement) MergeCreateChefRecipeMethodSupplement0(v CreateChefRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateChefRecipeMethodSupplement1 returns the union data inside the CreateChefRecipe_Method_Supplement as a CreateChefRecipeMethodSupplement1
func (t CreateChefRecipe_Method_Supplement) AsCreateChefRecipeMethodSupplement1() (CreateChefRecipeMethodSupplement1, error) {
	var body CreateChefRecipeMethodSupplement1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChefRecipeMethodSupplement1 overwrites any union data inside the CreateChefRecipe_Method_Supplement as the provided CreateChefRecipeMethodSupplement1
func (t *CreateChefRecipe_Method_Supplement) FromCreateChefRecipeMethodSupplement1(v CreateChefRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChefRecipeMethodSupplement1 performs a merge with any union data inside the CreateChefRecipe_Method_Supplement, using the provided CreateChefRecipeMethodSupplement1
func (t *CreateChefRecipe_Method_Supplement) MergeCreateChefRecipeMethodSupplement1(v CreateChefRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateChefRecipe_Method_Supplement) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateChefRecipe_Method_Supplement) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateUsrRecipeMethodSupplement0 returns the union data inside the CreateUsrRecipe_Method_Supplement as a CreateUsrRecipeMethodSupplement0
func (t CreateUsrRecipe_Method_Supplement) AsCreateUsrRecipeMethodSupplement0() (CreateUsrRecipeMethodSupplement0, error) {
	var body CreateUsrRecipeMethodSupplement0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateUsrRecipeMethodSupplement0 overwrites any union data inside the CreateUsrRecipe_Method_Supplement as the provided CreateUsrRecipeMethodSupplement0
func (t *CreateUsrRecipe_Method_Supplement) FromCreateUsrRecipeMethodSupplement0(v CreateUsrRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateUsrRecipeMethodSupplement0 performs a merge with any union data inside the CreateUsrRecipe_Method_Supplement, using the provided CreateUsrRecipeMethodSupplement0
func (t *CreateUsrRecipe_Method_Supplement) MergeCreateUsrRecipeMethodSupplement0(v CreateUsrRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateUsrRecipeMethodSupplement1 returns the union data inside the CreateUsrRecipe_Method_Supplement as a CreateUsrRecipeMethodSupplement1
func (t CreateUsrRecipe_Method_Supplement) AsCreateUsrRecipeMethodSupplement1() (CreateUsrRecipeMethodSupplement1, error) {
	var body CreateUsrRecipeMethodSupplement1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateUsrRecipeMethodSupplement1 overwrites any union data inside the CreateUsrRecipe_Method_Supplement as the provided CreateUsrRecipeMethodSupplement1
func (t *CreateUsrRecipe_Method_Supplement) FromCreateUsrRecipeMethodSupplement1(v CreateUsrRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateUsrRecipeMethodSupplement1 performs a merge with any union data inside the CreateUsrRecipe_Method_Supplement, using the provided CreateUsrRecipeMethodSupplement1
func (t *CreateUsrRecipe_Method_Supplement) MergeCreateUsrRecipeMethodSupplement1(v CreateUsrRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateUsrRecipe_Method_Supplement) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateUsrRecipe_Method_Supplement) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGetRecipeMethodSupplement0 returns the union data inside the GetRecipe_Method_Supplement as a GetRecipeMethodSupplement0
func (t GetRecipe_Method_Supplement) AsGetRecipeMethodSupplement0() (GetRecipeMethodSupplement0, error) {
	var body GetRecipeMethodSupplement0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetRecipeMethodSupplement0 overwrites any union data inside the GetRecipe_Method_Supplement as the provided GetRecipeMethodSupplement0
func (t *GetRecipe_Method_Supplement) FromGetRecipeMethodSupplement0(v GetRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetRecipeMethodSupplement0 performs a merge with any union data inside the GetRecipe_Method_Supplement, using the provided GetRecipeMethodSupplement0
func (t *GetRecipe_Method_Supplement) MergeGetRecipeMethodSupplement0(v GetRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsGetRecipeMethodSupplement1 returns the union data inside the GetRecipe_Method_Supplement as a GetRecipeMethodSupplement1
func (t GetRecipe_Method_Supplement) AsGetRecipeMethodSupplement1() (GetRecipeMethodSupplement1, error) {
	var body GetRecipeMethodSupplement1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetRecipeMethodSupplement1 overwrites any union data inside the GetRecipe_Method_Supplement as the provided GetRecipeMethodSupplement1
func (t *GetRecipe_Method_Supplement) FromGetRecipeMethodSupplement1(v GetRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetRecipeMethodSupplement1 performs a merge with any union data inside the GetRecipe_Method_Supplement, using the provided GetRecipeMethodSupplement1
func (t *GetRecipe_Method_Supplement) MergeGetRecipeMethodSupplement1(v GetRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetRecipe_Method_Supplement) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetRecipe_Method_Supplement) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUpdateRecipeMethodSupplement0 returns the union data inside the UpdateRecipe_Method_Supplement as a UpdateRecipeMethodSupplement0
func (t UpdateRecipe_Method_Supplement) AsUpdateRecipeMethodSupplement0() (UpdateRecipeMethodSupplement0, error) {
	var body UpdateRecipeMethodSupplement0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateRecipeMethodSupplement0 overwrites any union data inside the UpdateRecipe_Method_Supplement as the provided UpdateRecipeMethodSupplement0
func (t *UpdateRecipe_Method_Supplement) FromUpdateRecipeMethodSupplement0(v UpdateRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUpdateRecipeMethodSupplement0 performs a merge with any union data inside the UpdateRecipe_Method_Supplement, using the provided UpdateRecipeMethodSupplement0
func (t *UpdateRecipe_Method_Supplement) MergeUpdateRecipeMethodSupplement0(v UpdateRecipeMethodSupplement0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateRecipeMethodSupplement1 returns the union data inside the UpdateRecipe_Method_Supplement as a UpdateRecipeMethodSupplement1
func (t UpdateRecipe_Method_Supplement) AsUpdateRecipeMethodSupplement1() (UpdateRecipeMethodSupplement1, error) {
	var body UpdateRecipeMethodSupplement1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateRecipeMethodSupplement1 overwrites any union data inside the UpdateRecipe_Method_Supplement as the provided UpdateRecipeMethodSupplement1
func (t *UpdateRecipe_Method_Supplement) FromUpdateRecipeMethodSupplement1(v UpdateRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUpdateRecipeMethodSupplement1 performs a merge with any union data inside the UpdateRecipe_Method_Supplement, using the provided UpdateRecipeMethodSupplement1
func (t *UpdateRecipe_Method_Supplement) MergeUpdateRecipeMethodSupplement1(v UpdateRecipeMethodSupplement1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t UpdateRecipe_Method_Supplement) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UpdateRecipe_Method_Supplement) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
