// Package docs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package docs

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// FeaturedChef defines model for featuredChef.
type FeaturedChef struct {
	Data []struct {
		// ChefId シェフID
		ChefId openapi_types.UUID `json:"chefId"`

		// ImageUrl プロフィール画像
		ImageUrl *string `json:"imageUrl,omitempty"`

		// Name シェフ登録名
		Name string `json:"name"`

		// NumFollower フォロワー数
		NumFollower int `json:"numFollower"`

		// Score 注目度→実際のデータはscoreの降順でソートされる
		Score int `json:"score"`
	} `json:"data"`
}

// TrendRecipe defines model for trendRecipe.
type TrendRecipe struct {
	Data []struct {
		// ImageUrl レシピ画像
		ImageUrl *string `json:"imageUrl,omitempty"`

		// Introduction レシピの紹介文
		Introduction *string `json:"introduction,omitempty"`

		// Name レシピ名
		Name string `json:"name"`

		// NumFav ファボられ数
		NumFav int `json:"numFav"`

		// RecipeId レシピID
		RecipeId openapi_types.UUID `json:"recipeId"`

		// Score 話題度→実際のデータはscoreの降順でソートされる
		Score int `json:"score"`
	} `json:"data"`
}
