name: "CI"
on: ["push"]

jobs:
  ci:
    name: "Run CI"
    container:
      image: aopontann/dev_go_opencv:latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.3'

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"

    - name: install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    
    - name: run goimports
      run: goimports -d .