name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.3'

    - name: install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.3
    
    - name: run staticcheck
      run: staticcheck -checks inherit

    - name: install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    
    - name: run goimports
      run: goimports -d .