name: build_and_push_docker_image

on:
  workflow_dispatch:
  push:
    paths:
      - '.devcontainer/Dockerfile.opencv'
      - '.github/workflows/docker.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qin-recipe-team03:latest